<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ErrorOr" Version="2.1.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Mappers\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Http.Features">
        <HintPath>..\..\..\..\..\..\..\..\home\mitakii\.dotnet\packs\Microsoft.AspNetCore.App.Ref\10.0.10\ref\net10.0\Microsoft.AspNetCore.Http.Features.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
